version: '3.9'
services:
  palworld-dedicated-server:
    build: .
    container_name: palworld-dedicated-server
    image: 'jordanolivet/palworld-dedicated-server:latest'
    restart: always
    network_mode: bridge
    ports:
      - "8211:8211/udp"
    environment:
      - ALWAYS_UPDATE_ON_START=false
      - GAME_PORT=8211
      - MAX_PLAYERS=16
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=true
      - PUBLIC_IP=
      - PUBLIC_PORT=
      - RCON_PORT=25575
    volumes:
      - ./game:/palworld
